// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disonnect() {
  return window['go']['main']['App']['Disonnect']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function JoinLobby() {
  return window['go']['main']['App']['JoinLobby']();
}

export function LeaveLobby() {
  return window['go']['main']['App']['LeaveLobby']();
}
